enhancement-112: Improvements around the Transport Key (NK)
keylime/enhancements pull request #113
Opened 2024-09-25 10:46 UTC by THS-on

2024-11-19 21:21 UTC, maugustosilva commented on 112_nk_improvements.md
> +- Eliminate to NK fully (would require for us to force enable mTLS when using payloads)
In order to reach a point where we can make `mTLS` mandatory, we would need to provide a seamless certificate configuration/bootstrapping/rotation solution within Keylime (not sure what form such solution would take).

2024-11-19 21:21 UTC, maugustosilva approved these changes

2024-11-19 21:21 UTC, maugustosilva commented
I have read the proposal, and see that it contemplates the continued use of [Secure Payloads](https://keylime.readthedocs.io/en/latest/user_guide/secure_payload.html) for scenarios where the `mTLS` is disabled. That being said, I see no impediments on proceeding with it.

2025-04-01 14:00 UTC, ansasaki requested changes
I found a single typo, otherwise this looks good.

Since this would change the protocol messages between the components, it is necessary to restrict them to newer API versions, otherwise it would break when communicating with older versions. Probably we would need to support both mechanisms for a while.

I think this details should be registered in the upgrade/downgrade strategy section

2025-04-08 14:44 UTC, ansasaki commented on 112_nk_improvements.md
> +# When mTLS is disables
I added a commit to fix this.

2025-04-08 14:44 UTC, ansasaki approved these changes

2025-04-08 14:46 UTC, merged