Keylime dedicated user account enhancement proposal.
keylime/enhancements pull request #28
Opened 2020-10-14 10:23 UTC by axelsimon

Some sections remain to be fleshed out, but the core proposal is explained here.

Signed-off-by: axelsimon <github@axelsimon.net>

2020-10-14 15:39 UTC, mpeters requested changes
Just some minor changes

2020-10-14 15:39 UTC, mpeters commented on 23_dedicated_keylime_user_account.md
> +is whitelisted to run as root on the organisation's hosts, and Keylime is not
Should: Change "whitelisted" to something like "allowed"

2020-10-14 15:39 UTC, mpeters commented on 23_dedicated_keylime_user_account.md
> +#### Story 2
We can leave off the "Story 2", I think the first user story is definitely enough

2020-10-21 13:06 UTC, axelsimon commented on 23_dedicated_keylime_user_account.md
> +is whitelisted to run as root on the organisation's hosts, and Keylime is not
good point, thanks

2020-10-21 13:12 UTC, axelsimon commented
I think this updated version addresses @mpeters' comments. I have re-requested review.

2020-10-21 13:44 UTC, ashcrow commented on 23_dedicated_keylime_user_account.md
> +Privilege separation (and more generally, defense in depth) can be done at
Would containerization be an acceptable alternative as well (assuming SPC isn't required)?

2020-11-18 22:21 UTC, mpeters requested changes
Just some small typos

2020-11-18 22:21 UTC, mpeters commented on 23_dedicated_keylime_user_account.md
> +the rights necessary to run properlpy, but no more. As such, we want to
TYPO: Should be "properly"

2020-11-18 22:21 UTC, mpeters commented on 23_dedicated_keylime_user_account.md
> +possible from runnig as the root user to running as a dedicated user, called
TYPO: Should be "running"

2020-11-18 22:21 UTC, mpeters commented on 23_dedicated_keylime_user_account.md
> +regarding the software that may be run, and how, i would like to use Keylime for
TYPO: Should be "I" (capital)

2020-11-20 11:59 UTC, axelsimon commented on 23_dedicated_keylime_user_account.md
> +regarding the software that may be run, and how, i would like to use Keylime for
I've stopped capitalising my “i”, unless at the beginning of a sentence, but i won't fight anyone on this :)

2020-11-20 12:00 UTC, axelsimon commented
> Just some small typos

Thanks, nice catch. Fixed!

2020-11-20 17:58 UTC, merged